### ISSUE TITLE
brew install not working

### ISSUE THREAD

**Issue by chiol** [EOSIO/eosio.cdt#1134]
When I try to install eosio.cdt with brew on mac big sur, error is found. I love eosio, but it hurts me :sob: 
plz fix it 

![image](https://user-images.githubusercontent.com/21219546/123213209-b21ea080-d500-11eb-9bd1-8731918cadc6.png)

**Comment by hajunho** [comment]
I do, too, and 'brew style --fix' is not the solution. Error: Invalid formula: /usr/local/Homebrew/Library/Taps/eosio/homebrew-eosio.cdt/eosio.cdt.rb
eosio.cdt: Calling `sha256 "digest" => :tag` in a bottle block is disabled! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Error: Cannot tap eosio/eosio.cdt: invalid syntax in tap!

**Comment by hubts** [comment]
This problem was from the recent OS update. 
In my case, the recent MAC OS X update occurs the problem. 
Now we can use the installation command on MAC.

~~~bash
~ ❯ brew tap eosio/eosio.cdt                                        09:05:08 AM
brew install eosio.cdt
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from dc2c0ec8c to 3ffa2e68c.
Updated 5 taps (heroku/brew, homebrew/core, homebrew/cask, homebrew/cask-fonts and eosio/eosio.cdt).
==> New Formulae
detect-secrets      frum                git-xargs           ronn
==> Updated Formulae
Updated 525 formulae.
==> New Casks
adrive                     openloco                   shimonote
==> Updated Casks
Updated 144 casks.

==> Downloading https://github.com/eosio/eosio.cdt/releases/download/v1.8.0/eosi
Already downloaded: /Users/kimts/Library/Caches/Homebrew/downloads/85c94fda5e7ff8e97f9227e5458b44282020836311262fab4bf93fcd723c2f0e--eosio.cdt-1.8.0.catalina.bottle.tar.gz
==> Pouring eosio.cdt-1.8.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/eosio.cdt/1.8.0: 4,005 files, 369.2MB
~ ❯ eosio-init --version                                            
eosio-init version 1.8.0
~~~

**Comment by chiol** [comment]
good enjoy yourself
