### ISSUE TITLE
Why is only a stripped down Version of Boost available in the cdt.

### ISSUE THREAD

**Issue by cmadh** [EOSIO/eosio.cdt#203]
Why is only a stripped down Version of Boost available in the eosio.cdt while with the old eosiocpp full boost-libs where available. Also, doesn't this mean that there's a big lack in backwards-compatibilty?

**Comment by larryk85** [comment]
Yes, v1.3.0 is not backwards compatible with v1.2.x of eosio.cdt and no way backwards compatible with eosiocpp.  The reason is because Boost inclusion is being phased out of eosio.cdt, the subset that is currently in use in eosio.cdt is the bare minimum that is needed to get certain functionality to work correctly in eosiolib.  But, even these will be removed when suitable in-house replacements are made.  The reason for the phase out itself is that eosio.cdt shouldn't rely on Boost (this is a toolchain and set of standard libraries), and is a large surface area to audit to ensure that Boost does the right thing for contract development.  If the contract writer (i.e. you) wants full Boost, you can maintain your own copy and tell the compiler where to look with `-I<path to Boost>`, like any other toolchain.
