### ISSUE TITLE
Compile error in libaries/eosiolib/fixed_key.hpp

### ISSUE THREAD

**Issue by keisuke-kanao** [EOSIO/eosio.cdt#251]
I got a compile error below:
<pre>
/usr/local/eosio.cdt/bin/../include/eosiolib/fixed_key.hpp:66:23: error: cannot initialize a variable of type
      'unsigned long long' with an lvalue of type 'unsigned long long *'
            for( Word w_itr = arr_begin; w_itr != arr_end; ++w_itr ) {
</pre>
This should be:
<pre>
for( Word* w_itr = arr_begin; w_itr != arr_end; ++w_itr ) {
</pre>

**Comment by arhag** [comment]
You are correct. That is unfortunate, since v1.4.0 of eosio.cdt was not intended to be a breaking release.

By the way, `eosio::fixed_key` has been deprecated in favor of `eosio::fixed_bytes` (a nearly identical replacement with the exception of some bug fixes), and this bug is not present in the `eosio::fixed_bytes` implementation.

**Comment by keisuke-kanao** [comment]
Thank you for your additional info.

**Comment by arhag** [comment]
Resolved by #255.
