### ISSUE TITLE
Got this error:/usr/opt/eosio.cdt/1.3.2/bin/wasm-ld: error: membership.wasm: undefined symbol: std::__1::chrono::system_clock::to_time_t(std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1ll, 1000000ll> > > const&) /usr/opt/eosio.cdt/1.3.2/bin/wasm-ld: error: membership.wasm: undefined symbol: gmtime

### ISSUE THREAD

**Issue by elmzlab** [EOSIO/eosio.cdt#340]
Got this error:/usr/opt/eosio.cdt/1.3.2/bin/wasm-ld: error: membership.wasm: undefined symbol: std::__1::chrono::system_clock::to_time_t(std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1ll, 1000000ll> > > const&)
/usr/opt/eosio.cdt/1.3.2/bin/wasm-ld: error: membership.wasm: undefined symbol: gmtime

I am using the standard gmtime function and chrono functions. Compiles successfully fails in the build. Can someone help me pls, been at it for 2 days now?

**Comment by maoueh** [comment]
Your smart contract has access to a limited API, and `gmtime` is not part of it. It compiles but once linking it, it cannot find the definition. Even if you would fix the linking step, you would probably to be able to execute it later on since the actual code won't be available in the runtime environment of the smart contract.

To work with time related stuff, you have access to [time_point](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/time.hpp#L38) (microseconds granularity) and [time_point_sec](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/time.hpp#L62) (seconds granularity) from the [time.hpp](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/time.hpp) header.

To have a `time_point` or `time_point_sec` initiated at current time, use [current_time](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/system.h#L79) (microseconds) or [now](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/system.h#L86) from the [system.h](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/system.h) header.

```
#include <eosiolib/time.hpp>
#include <eosiolib/system.h>

auto nowWithMicroseconds = time_point(current_time())
auto nowWithSeconds =  time_point_sec(now())
```

Check the [time.hpp](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/time.hpp) file to see how you can manipulate each object.

Hope it helps.
