### ISSUE TITLE
How to improve the efficiency of smart contract execution

### ISSUE THREAD

**Issue by Acmefocus** [EOSIO/eosio.cdt#433]
How to improve the efficiency of smart contract execution？
C++ programs outside the contract are very efficient, but the efficiency of running within the contract is six times slower. Is there any way to reduce the difference between them?

**Comment by larryk85** [comment]
This is a very subjective question, and needs a bit of elaboration on your part.  What do you mean by the statement `C++ programs outside the contract`? Does this mean native C++ programs or running on some other WASM runtime?  If you are seeing a 6x performance decrease and you are comparing to a native program, then I would say that seems likely to be the case.  WASM is designed to be secure, as such a proper WASM runtime has to do (albeit trivial) type checking, control flow can only move in one direction (forward), and the whole architecture is a specialized stack machine.  In saying those points the compiler will be unable to do certain optimizations that a natively compiled program that is targeting a generalized 2/3 address instruction set.  Also, in saying that we always have a main goal of minimizing the gap with each iteration of the CDT and on the eos side.

**Comment by lifu568** [comment]
@larryk85  ， hi！
Thank you very much for receiving your reply. I refer to the native c++ programs compared to the contract. We want to put the native range proof verification program into a smart contract. It only takes 11 milliseconds to execute the program native, but it times out in the smart contract. Do you have a good solution? I want to hide the transaction amount on the chain. I don't know if you have a way to hide the transaction data or the transaction amount on the chain. Will you develop hidden transaction data or transaction amount later?

**Comment by johndebord** [comment]
@lifu568
I think you are misunderstanding the paradigm of distributed ledger technology.
If it were possible to hide transaction data, then how could said data be distributed to the network?
Could a consensus between parties be established if the transactions are not known to all participants?

Now, there are certain protocols that do have this feature, but not the EOSIO protocol.
Is it possible for there to be some sort of feature like this in the future? Yes, anything is possible.
But as for the state of the protocol right now, there is absolutely no way to hide a transaction.

Instead of focusing on _hiding_ data, focus on _making data known_ and leverage that.

**Comment by lifu568** [comment]
@larryk85  @johndebord  @dskvr  @arhag @zreyn 
The application of enterprise users in the blockchain is mainly in the form of a federated chain, because this ensures data privacy, and only the members of the alliance can find the data on the chain. If the public chain is to be used for enterprise applications, data privacy issues need to be addressed. We want to expand the scope of EOS applications and adapt to enterprise-level applications. That is to say, you want to be an enterprise-level vpn on the public chain blockchain. On the public chain, you can apply it to enterprise applications by developing smart contracts. If this can be achieved, it can help many enterprise applications go to the EOS ecosystem and enhance the EOS user community. At present, we have studied the experiment and hidden the transaction amount in the EOS smart contract, but encountered some technical problems and it is difficult to solve.
We hide the transaction amount in the smart contract. For example: Alice transfers Bob, turns 30, we want to hide the balance of Alice and Bob, and the transfer amount of 30. The method we experimented with was to use the homomorphic addition and subtraction to calculate the balance, and use the scope proof to verify whether the alice's balance was greater than 0 after the transfer of 30 . The homomorphic addition and subtraction, we have implemented within the EOS smart contract. However, the scope proof verification cannot be completed within the EOS smart contract because it performs a timeout within the smart contract. Do not know if you have a good way? Or provide a solution to the data amount hiding scheme in the EOS smart contract.
