### ISSUE TITLE
How to make PR accepted

### ISSUE THREAD

**Issue by conr2d** [EOSIO/eosio.cdt#501]
Hi, @larryk85.
I really appreciate your efforts to make and improve CDT. I'm sorry that I made a lot of noises (PR) which cannot be merged. Some patches resolve issues in wrong way, and others may not fit in your plan.
However, sometimes even though the contents of my patch are applied, but its application is not by merging PR, but writing new commit. For open source contributors, finding their name from the list of commits is a little pleasure. If you don't mind, can you tell me the policy of contribution in "eosio.cdt" so that open source contributors (including me) make proper PR which can be merged to repository?
I understand you might be too busy to review PR in poor quality, but what about giving people a chance to improve their patches to grow up to be experienced ones like you? :)

**Comment by larryk85** [comment]
Hey, I'm sorry conr2d. It wasn't my intention to rob you of that.  We have had some problems with some of the last releases with submodule changes flying in under the radar and not being tracked appropriately, so I was trying to mitigate that.  I will be more mindful and personally evaluate yours and anyone else's PRs that is currently in the pull requests section and merge those directly.  There is a new safeguard that got put in place last week, so that new PRs will not have this issue.  So, please continue to PR and I will gladly merge those into the code base if they make sense and comment for you to make the appropriate changes if they need to be made.

**Comment by conr2d** [comment]
@larryk85 No problem. Thank you for your kind response! 👍
